version: "3.9"

services:
  database_rental:
    image: postgres
    container_name: database_rental
    restart: always
    ports:
      - 3434:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rental
    volumes:
      - pgdata:/data/postgres
      
  app:
    build: .
    container_name: rental
    ports:
      - 3333:3333

volumes: 
  pgdata: 
    driver: local