version: "3.9"

services:
  database:
    image: postgres
    container_name: database_rental
    restart: always
    ports:
      - 3434:3434
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rental
    volumes:
      - pgdata:/data/postgres
    command: -p 3434
      
  app:
    build: .
    container_name: rental
    ports:
      - 3333:3333
      - 9229:9229
    links: 
      - database
    depends_on: 
      - database
    volumes:
      - .:/usr/app

volumes: 
  pgdata: 
    driver: local